name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the feature you'd like to see
      placeholder: I'd like to have a component that...
    validations:
      required: true

  - type: dropdown
    id: component-type
    attributes:
      label: Component Type
      description: What type of component are you requesting?
      options:
        - New settings component
        - Enhancement to existing component
        - New API/functionality
        - Documentation improvement
        - Build/tooling improvement
        - Other
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which module should this feature belong to?
      options:
        - ui-tiles (core components)
        - ui-tiles-extended (advanced components)
        - ui-tiles-expressive (expressive Material 3)
        - ui-core (foundation/shared)
        - New module
        - Not sure
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Provide example use cases for this feature
      placeholder: |
        1. User wants to configure multiple related settings at once
        2. App needs to show a visual indicator for premium features
        3. Settings screen needs better organization
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Proposed API (Optional)
      description: If you have an idea of how the API should look, show us
      render: kotlin
      placeholder: |
        @Composable
        fun SettingsYourComponent(
            title: @Composable () -> Unit,
            // ... parameters
        ) {
            // Usage example
        }
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I tried using X component, but it doesn't support Y
    validations:
      required: false

  - type: dropdown
    id: platforms
    attributes:
      label: Target Platforms
      description: Which platforms should support this feature?
      multiple: true
      options:
        - Android
        - iOS
        - Desktop (JVM)
        - JavaScript
        - WebAssembly
        - All platforms
    validations:
      required: true

  - type: textarea
    id: design
    attributes:
      label: Design Reference
      description: Add mockups, screenshots, or links to design examples
      placeholder: Drag and drop images or paste links here
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my project
        - Blocking my work
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or information
      placeholder: This feature exists in library X but not in Compose-Settings
    validations:
      required: false

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I am willing to submit a pull request for this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this hasn't been requested before
          required: true
        - label: This feature aligns with the library's purpose (UI components for settings screens)
          required: true
